### ISSUE TITLE
Flagged by gabbar?

### ISSUE THREAD

**Issue by mvexel** [mapbox/gabbar#10]
In osmcha I see [some of my edits are `flagged by gabbar`](https://osmcha.mapbox.com/?usernames=mvexel&is_suspect=True&is_whitelisted=True&harmful=False&checked=All) which I suspect is this thing. It is not immediately clear to me by what mechanism edits are flagged and what this means. Some clarification would be wonderful.

**Comment by bkowshik** [comment]
👋 @mvexel, thank you for getting in touch.

Yes, changesets with reason `Flagged by gabbar` do come from `gabbar`. This is **EXPERIMENTAL: UNDER DEVELOPMENT** and we will update the README soon with [this PR](https://github.com/mapbox/gabbar/pull/9).

> Gabbar is an alpha package of a pre-trained binary problematic/not problematic classifier that was trained on manually labelled changesets from OpenStreetMap.

Currently, we are exploring if changesets can be classified as 👍 or 👎 by looking at the number features created, modified and deleted in a changeset. We have a model that given these three values will tell whether a changeset is a 👍 or not based on it's training on the changesets @manoharuss shared with the community in this [diary post](http://www.openstreetmap.org/user/manoharuss/diary/40118).

We are at very early stages understanding the behavior of the trained model. The goal is to use all the learning's from the changesets manually reviewed by mapbox/team-data and the OpenStreetMap community on `osmcha` and build a machine learning based classifier.

### Hyperlinks
- [Test cases for testing the predictions from `gabbar`](https://github.com/mapbox/gabbar/blob/master/tests/test_mod.py)
- [Documentation on how the model was trained](https://github.com/mapbox/gabbar/blob/master/README.md#model-training)

**Comment by bkowshik** [comment]
No next actions here. Closing.
