### ISSUE TITLE
Understanding validation and vandalism detection work on Wikipedia

### ISSUE THREAD

**Issue by bkowshik** [mapbox/gabbar#13]
*NOTE: This is a work in progress. Posting here to start discussion around the topic*

---

Wikimedia uses Artificial Intelligence for the following broad categories:
- Vandalism detector. Use edit statistics to find correlations and predict if an edit is problematic.
- Article edit recommender. Use user edit history to predict which articles could be edited by user.
- Article quality prediction. To assess quality of articles on Wikipedia.

On Wikipedia there are 160k edits, 50k new articles and 1400 new editors everyday. The goal is to split the 160k edits into:
1. Probably OK, almost certainly not vandalism
2. Needs manual review, might possibly be vandalism

## Themes for validation
- Points of view or standpoint:
    - Wikipedia is a firehose
    - Bad edits must be reverted
    - Minimize manual effort wasted on quality control work
    - **Socialize and train newcomers**
- Design tools for Empowerment vs a Power over.
    - Empowerment: I want to hear you, so I'll make space for you to speak and listen.
    - Power over: I want to set the tone of our conversation by talking first.
- A flipped publication model: *Publish first and review later.*
- *Given enough eyeballs, all bugs are shallow.* If we have a large enough group of people looking at something, somebody will know the tight way to solve the problem.

### Welcoming newcomers
More newcomers is a major Wikimedia goal and new spaces have been developed to support newcomers. Quality control in Wikipedia is being designed with newcomer socialization in mind so that newcomers (especially those who don't conform) are not marginalized and good-faith newcomers are retained. Although anonymous edits on Wikipedia are twice as likely to be vandalism, 90% of anonymous edits are good.

From this [Slate article](http://www.slate.com/articles/technology/future_tense/2017/03/wikipedia_s_battle_over_very_short_articles.html):

> Most people first get involved with Wikipedia—one of the largest social movements in history—by making some minor corrections or starting a small article that is missing. If their contributions get deleted, especially if there is no sufficient explanation why, they are likely to quit. It is quite destructive to the community’s long-term survival, as Wikipedia has struggled for quite a while with editor retention.

## Popular validation tools

There are around 20 volunteer developed tools, 3 major Wikimedia product initiatives. Some popular ones are:

- [Objective Revision Evaluation Service (ORES)](https://meta.wikimedia.org/wiki/Objective_Revision_Evaluation_Service) is intended to provide a generalized service to support quality control and curation work in all wikis.
    - **Edit quality models** for predicting whether or not an edit cause damage, was saved in good-faith or will eventually be reverted.
    - **Article quality models** that helps gauge progress and identify missed opportunities (popular articles that are low quality). [Wikipedia 1.0 assessment](https://en.wikipedia.org/wiki/WP:Wikipedia_1.0)
- [Huggle](https://en.wikipedia.org/wiki/Wikipedia:Huggle), a diff browser intended for dealing with vandalism and other un-constructive edits on Wikimedia projects.
- [STiki](https://en.wikipedia.org/wiki/Wikipedia:STiki), a tool used to detect and revert vandalism or other un-constructive edits on Wikipedia, available to trusted users.
- [User:ClueBot NG](https://en.wikipedia.org/wiki/User:ClueBot_NG), an anti-vandal bot that tries to detect and revert vandalism quickly and automatically. A 0.1% false-positive rate and able to detect 40% of all vandalism.

Basic web interface for ORES at https://ores.wikimedia.org/ui Some of the features used to aid classification of a revision as problematic or not are: Is user anonymous, number of characters/words added, modified and removed, number of repeated characters and bad words added. Prediction scores for a problematic revision look like below:

https://ores.wmflabs.org/scores/enwiki/damaging/642215410

![](https://wikimediablog.files.wordpress.com/2015/11/image01.png)

```json
{
  "642215410": {
    "prediction": true,
    "probability": {
      "false": 0.11271979528262599,
      "true": 0.887280204717374
    }
  }
}
```

There has been quite a lot of research in this field evident from the number of results on [Google scholar about Wikipedia vandalism detection](https://scholar.google.com/scholar?q=wikipedia+vandalism+detection&btnG=&hl=en&as_sdt=0%2C24).

## Hyperlinks

Reading
- [Wikimedia blog post on ORES](https://blog.wikimedia.org/2015/11/30/artificial-intelligence-x-ray-specs/)
- [What should an AI do you for you? Building an AI Wishlist](https://etherpad.wikimedia.org/p/devsummit17-AI_wishlist)

Videos
- [Engineering at the Intersection of Productive Efficiency, Ideology, and Ethical AI in Wikipedia](https://www.youtube.com/watch?v=LYF-3t14CSc)

---

cc: OpenStreetMap Community

**Comment by planemad** [comment]
Awesome research into Vandalism detection on Wikipedia @bkowshik . The wiki community have a [mature bot policy](https://en.wikipedia.org/wiki/Wikipedia:Bot_policy) and encourage focused and effective mechanical editing that has built community curated ecosystem of AI workers that has been highly effective in quickly fixing the most common problems to occur. A large academic community is interested in the mechanics of this and the associated research has further helped to strengthen the defenses

To compare, the [OSM Automated Edits Policy](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct) has not evolved much. Validation is a good angle to have some bots running to catch simple issues like a invalid capitalization in a tag like `Highway=residential`

**Comment by bkowshik** [comment]
> You can check a model's statistics by dropping the revision ID from the path.

- https://ores.wmflabs.org/scores/enwiki/reverted/
```json
{
	"params": {
		"balanced_sample": false,
		"balanced_sample_weight": true,
		"center": true,
		"init": null,
		"learning_rate": 0.01,
		"loss": "deviance",
		"max_depth": 7,
		"max_features": "log2",
		"max_leaf_nodes": null,
		"min_samples_leaf": 1,
		"min_samples_split": 2,
		"min_weight_fraction_leaf": 0.0,
		"n_estimators": 700,
		"presort": "auto",
		"random_state": null,
		"scale": true,
		"subsample": 1.0,
		"verbose": 0,
		"warm_start": false
	},
	"table": {
		"false": {
			"false": 15563,
			"true": 2551
		},
		"true": {
			"false": 457,
			"true": 962
		}
	},
	"precision": {
		"false": 0.971,
		"true": 0.274
	},
	"trained": 1491356274.077835,
	"type": "GradientBoosting",
	"version": "0.3.0"
}
```

**Comment by bkowshik** [comment]
This has been super-helpful. No next actions here. Closing.
