### ISSUE TITLE
Increasing number of changesets flagged

### ISSUE THREAD

**Issue by bkowshik** [mapbox/gabbar#4]
For the last two days that `gabbar` has been live on `osmcha-staging`, it has flagged less than 30 changesets as problematic everyday. In the real-world, there could potentially be more changesets that are harmful. So:

- How can we increase the number of changesets flagged by `gabbar`?
- How can we bring accuracy down a little so that we bring number of false negatives down?

---

cc: @rodowi

**Comment by rodowi** [comment]
> How can we increase the number of changesets flagged by gabbar?

by decreasing [precision](https://en.wikipedia.org/wiki/Precision_and_recall)

**Comment by danstowell** [comment]
Hi - an osmcha user here. I see many dozens of "flagged by gabbar", and I'm only looking at a localish area - I don't think you want to increase the amount too much.

You say "bring accuracy down a little", but that can't be right. You want to increase the accuracy, in general. I guess you mean you want to change the threshold, i.e. change the balance of false-positive and false-negative. But I go back to my first point - do consider the risk of flooding osmcha!

**Comment by bkowshik** [comment]
:wave: @danstowell happy to meet a fellow osmcha user. 😃 

`gabbar` is a super-experimental machine learning based changeset classifier to identify problematic edits on OpenStreetMap. We deployed to `osmcha-django-production` over the weekend, but it turned out to be super noisy and as a result we have brought it down. We will take the next couple of days to iterate on the classifier and bring back an improved version of `gabbar` to osmcha-django.

> I guess you mean you want to change the threshold.

Thank you for clarifying. I meant changing the threshold of the classifier.

**Comment by bkowshik** [comment]
No next actions here. Closing.
