### ISSUE TITLE
Translating names to English for validation using external APIs

### ISSUE THREAD

**Issue by bkowshik** [mapbox/gabbar#42]
*NOTE: Posting here to document a potential idea.*

---

In [changeset 48269805](https://osmcha.mapbox.com/48269805/), there was one feature that was modified:

- The name of the marketplace was modified from English to Chinese

<img width="1170" alt="screen shot 2017-05-23 at 12 56 03 pm" src="https://cloud.githubusercontent.com/assets/2899501/26342831/378c43a0-3fb7-11e7-9da2-cd5252afc801.png">

I gave [Google Translate API](https://cloud.google.com/translate/docs/) a try to translate the new name `亚庇中央巴刹`, back to English. The result was `Kota Kinabalu`. These two words match with the English name in the previous version of the feature, `Pasar Kota Kinabalu Central`.

```js
'use strict';

const Translate = require('@google-cloud/translate');
const projectId = 'Insert project ID';
const translateClient = Translate({
    projectId: projectId
});

translateClient.translate('센트럴마켓', 'en')
.then((results) => {
    const translation = results[0];

    console.log(`Text: ${text}`);
    console.log(`Translation: ${translation}`);
})
.catch((err) => {
    console.error('ERROR:', err);
});
```

**Comment by lukasmartinelli** [comment]
I don't think that should fit into Gabbar but into other systems.

**Comment by bkowshik** [comment]
Yes @lukasmartinelli, an external system makes more sense. No next actions here. Closing.
